# Generated by Django 3.2.9 on 2021-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_person_mobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mydoc',
            field=models.BooleanField(default=False),
        ),
    ]
