# Generated by Django 3.2.9 on 2021-12-27 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_person_mydoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mydoc',
        ),
        migrations.AddField(
            model_name='person',
            name='mydoc',
            field=models.ManyToManyField(default=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
